#!/usr/bin/env python3
"""
Interactive (and scriptable) credential setup for the Cisco APIC MCP server.

Run once, in a terminal, before registering the MCP server with your client:

    uv run python app/setup.py                     # interactive wizard
    uv run python app/setup.py --auth-method cert
    uv run python app/setup.py --auth-method keyring --username svc-aci
    uv run python app/setup.py --auth-method dotenv

The chosen method is recorded (non-secret) in the .env file as APIC_AUTH_METHOD.
Secrets are handled per method:
  * cert    - a keypair is generated; the private key is written to a file
              (chmod 600) and the public certificate is printed for you to
              register in APIC. No password is stored.
  * keyring - the password is stored in the OS credential manager
              (Windows Credential Manager / macOS Keychain / libsecret).
  * dotenv  - the password is written to .env in plaintext (least secure).

Because a STDIO MCP server speaks the protocol over stdin/stdout, it cannot
prompt for credentials at launch. This standalone command is that prompt.
"""

import argparse
import getpass
import os
import sys

# Run from anywhere: resolve paths relative to this file (the app/ directory).
APP_DIR = os.path.dirname(os.path.abspath(__file__))
ENV_PATH = os.path.join(APP_DIR, ".env")
CERTS_DIR = os.path.join(APP_DIR, "certs")

KEYRING_SERVICE = "APICmcp"
VALID_METHODS = ("cert", "keyring", "dotenv")


def _read_env() -> dict:
    """Parse the existing .env into a dict (best effort; preserves nothing else)."""
    values = {}
    if os.path.isfile(ENV_PATH):
        with open(ENV_PATH, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, _, val = line.partition("=")
                values[key.strip()] = val.strip().strip('"').strip("'")
    return values


def _write_env(values: dict) -> None:
    """Write the .env file from a dict of non-secret (and, for dotenv, secret) keys."""
    lines = ["# Generated by app/setup.py — configuration for the APIC MCP server.\n"]
    for key, val in values.items():
        if val is None:
            continue
        lines.append(f"{key}={val}\n")
    with open(ENV_PATH, "w", encoding="utf-8") as f:
        f.writelines(lines)
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass
    print(f"Wrote {ENV_PATH}")


def _prompt_method() -> str:
    print("\nHow should the MCP server authenticate to APIC?\n")
    print(
        "  1) Certificate (X.509 signature auth — no password stored)   [recommended]"
    )
    print("  2) OS credential manager (Keychain / Credential Mgr / libsecret)")
    print("  3) .env file (plaintext — not recommended)\n")
    choice = input("Select 1/2/3 [1]: ").strip() or "1"
    return {"1": "cert", "2": "keyring", "3": "dotenv"}.get(choice, "cert")


def _prompt_common(env: dict, args) -> tuple:
    base_url = (
        args.base_url
        or input(
            f"APIC base URL [{env.get('APIC_BASE_URL', 'https://apic.example.com')}]: "
        ).strip()
        or env.get("APIC_BASE_URL", "")
    )
    username = (
        args.username
        or input(f"APIC username [{env.get('APIC_USERNAME', '')}]: ").strip()
        or env.get("APIC_USERNAME", "")
    )
    if not base_url or not username:
        sys.exit("APIC base URL and username are required.")
    return base_url, username


def _setup_dotenv(env, args) -> dict:
    base_url, username = _prompt_common(env, args)
    # Allow scripted use: read from APIC_PASSWORD env if present, else prompt (no echo).
    password = os.getenv("APIC_PASSWORD") or getpass.getpass("APIC password: ")
    if not password:
        sys.exit("A password is required for the dotenv method.")
    print("\nWARNING: the password will be stored in plaintext in .env.\n")
    return {
        "APIC_BASE_URL": base_url,
        "APIC_USERNAME": username,
        "APIC_AUTH_METHOD": "dotenv",
        "APIC_PASSWORD": password,
    }


def _setup_keyring(env, args) -> dict:
    try:
        import keyring
    except ImportError:
        sys.exit(
            "The 'keyring' package is required. Install it with 'pip install keyring'."
        )
    base_url, username = _prompt_common(env, args)
    password = os.getenv("APIC_PASSWORD") or getpass.getpass(
        "APIC password (stored in OS keychain): "
    )
    if not password:
        sys.exit("A password is required for the keyring method.")
    keyring.set_password(KEYRING_SERVICE, username, password)
    print(
        f"Stored password for '{username}' in the OS credential manager "
        f"(service '{KEYRING_SERVICE}')."
    )
    return {
        "APIC_BASE_URL": base_url,
        "APIC_USERNAME": username,
        "APIC_AUTH_METHOD": "keyring",
    }


def _setup_cert(env, args) -> dict:
    try:
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
        from cryptography import x509
        from cryptography.x509.oid import NameOID
    except ImportError:
        sys.exit(
            "The 'cryptography' package is required. Install it with 'pip install cryptography'."
        )
    import datetime

    base_url, username = _prompt_common(env, args)
    cert_name = (
        args.cert_name
        or input("Certificate name to register in APIC [mcp-cert]: ").strip()
        or "mcp-cert"
    )

    os.makedirs(CERTS_DIR, exist_ok=True)
    key_file = os.path.join(CERTS_DIR, f"{username}-{cert_name}.key")
    crt_file = os.path.join(CERTS_DIR, f"{username}-{cert_name}.crt")

    if os.path.isfile(key_file) and not args.force:
        sys.exit(f"Key already exists: {key_file}. Re-run with --force to overwrite.")

    # Generate an RSA keypair and a self-signed certificate. APIC only needs the
    # public certificate attached to the local user; the key stays on this host.
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = issuer = x509.Name(
        [x509.NameAttribute(NameOID.COMMON_NAME, f"{username}-{cert_name}")]
    )
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.datetime.utcnow())
        .not_valid_after(datetime.datetime.utcnow() + datetime.timedelta(days=3650))
        .sign(key, hashes.SHA256())
    )

    with open(key_file, "wb") as f:
        f.write(
            key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )
    os.chmod(key_file, 0o600)
    cert_pem = cert.public_bytes(serialization.Encoding.PEM).decode()
    with open(crt_file, "w", encoding="utf-8") as f:
        f.write(cert_pem)

    print(f"\nPrivate key written to: {key_file} (chmod 600 — keep this secret)")
    print(f"Certificate written to: {crt_file}\n")
    print("=" * 70)
    print("Register this certificate in APIC:")
    print(f"  Admin > AAA > Users > {username} > User Certificates > add")
    print(f"  Name : {cert_name}")
    print("  Data : (paste the certificate below)")
    print("=" * 70)
    print(cert_pem)

    return {
        "APIC_BASE_URL": base_url,
        "APIC_USERNAME": username,
        "APIC_AUTH_METHOD": "cert",
        "APIC_CERT_NAME": cert_name,
        "APIC_CERT_KEY_FILE": key_file,
    }


def main():
    parser = argparse.ArgumentParser(
        description="Configure APIC MCP server credentials."
    )
    parser.add_argument(
        "--auth-method",
        choices=VALID_METHODS,
        help="Non-interactive: choose the credential backend.",
    )
    parser.add_argument(
        "--base-url", help="APIC base URL, e.g. https://apic.example.com"
    )
    parser.add_argument("--username", help="APIC username.")
    parser.add_argument(
        "--cert-name", help="Certificate name to register in APIC (cert method)."
    )
    parser.add_argument(
        "--force", action="store_true", help="Overwrite an existing key (cert method)."
    )
    args = parser.parse_args()

    env = _read_env()
    method = args.auth_method or _prompt_method()

    if method == "dotenv":
        values = _setup_dotenv(env, args)
    elif method == "keyring":
        values = _setup_keyring(env, args)
    else:
        values = _setup_cert(env, args)

    # Preserve any pre-existing non-secret settings we don't manage explicitly.
    if os.getenv("APIC_VERIFY_SSL"):
        values["APIC_VERIFY_SSL"] = os.getenv("APIC_VERIFY_SSL")
    elif "APIC_VERIFY_SSL" in env:
        values["APIC_VERIFY_SSL"] = env["APIC_VERIFY_SSL"]

    _write_env(values)
    print(
        f"\nDone. Auth method set to '{method}'. "
        "Register the MCP server and it will use this configuration."
    )


if __name__ == "__main__":
    main()
